package com.ex.model;

import javax.persistence.*;

/**
 * @author that-team
 * This class defines an item. An item can be placed as a geocache by a user and then
 * retrieved by other users. We anticipate that many items will be picked up and placed
 * into the world again, as is customary in the geocaching scene.
 *
 * @param itemID -  a unique, identifying number for the item, generated by the Database
 * @param itemName  - user defines the name to be displayed for the item
 * @param description  - user may write a short description of the item and how to find it
 * @param date - this date refers to the last time this item was touched, either when it was
 *             placed or when it was retrieved
 * @param imageurl  - a picture of where the item is located, uploaded by the user who places it,
 *              intended to assist other users when looking for it
 * @author Jordan Severance
 * @author Daniel Wallace
 */
@Entity
@Table(name="\"Items\"", schema = "\"that-team_schema\"")
public class Item {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "item_id")
    private int itemID;

    @Column(name = "item_name")
    private String itemName ;

    @Column(name = "description")
    private String description ;

    @Column(name = "imageurl")
    private String imageurl ;

    @OneToOne(mappedBy = "itemID", cascade = CascadeType.ALL)
    private GeoCashe geoCashe;

    public Item(){}

    public Item(String name, String description, String image) {
        this.itemName  = name;
        this.description = description;
        this.imageurl  = image;
    }

    public void setItemID(int itemID) {
        this.itemID = itemID;
    }

    public int getItemID() {
        return itemID;
    }

    public String getName() {
        return itemName ;
    }

    public void setName(String name) {
        this.itemName  = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImage() {
        return imageurl ;
    }

    public void setImage(String image) {
        this.imageurl  = image;
    }

}
